const listingsData = [
  {
    address: "colombia",
    neighborhood: "cali",
    date: "7/1/2019",
    state: "MO",
    rooms: 3,
    bath: 3,
    price: 560000,
    floorSpace: 3650,
    finished_basement: true,
    two_car_garage: true,
    houseType: "",
    image: "assets/img/1.jpg",
  },
  {
    address: "colombia",
    neighborhood: "cali",
    date: "7/1/2019",
    state: "MO",
    rooms: 3,
    bath: 3,
    price: 560000,
    floorSpace: 3650,
    finished_basement: true,
    two_car_garage: true,
    houseType: "",
    image: "assets/img/2.jpg",
  },
  {
    address: "colombia",
    neighborhood: "cali",
    date: "7/1/2019",
    state: "MO",
    rooms: 3,
    bath: 3,
    price: 560000,
    floorSpace: 3650,
    finished_basement: true,
    two_car_garage: true,
    houseType: "",
    image: "assets/img/3.jpg",
  },
  {
    address: "colombia",
    neighborhood: "cali",
    date: "7/1/2019",
    state: "MO",
    rooms: 3,
    bath: 3,
    price: 560000,
    floorSpace: 3650,
    finished_basement: true,
    two_car_garage: true,
    houseType: "",
    image: "",
  },
];
export default listingsData;
